# Generated by Django 4.1.5 on 2023-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='chegirma',
            field=models.SmallIntegerField(),
        ),
    ]
