# Generated by Django 4.1.5 on 2023-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_mahsulot_chegirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='reyting',
            field=models.SmallIntegerField(),
        ),
    ]
