# Generated by Django 4.2 on 2023-04-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_profil_tugilgan_yil'),
        ('buyurtma', '0003_delete_buyurtma_savatitem_yetkazish_puli_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(max_length=30)),
                ('sana', models.DateField(auto_now_add=True)),
                ('summa', models.IntegerField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.savat')),
            ],
        ),
    ]
