# Generated by Django 4.2 on 2023-04-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0004_buyurtma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='summa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
