# Generated by Django 4.2 on 2023-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0005_alter_buyurtma_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savatitem',
            name='yetkazish_puli',
            field=models.SmallIntegerField(default=30000),
        ),
    ]
