# Generated by Django 4.1.5 on 2023-04-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('rasm', models.FileField(max_length=50, upload_to='')),
                ('tel', models.CharField(max_length=20)),
                ('tugilgan_yil', models.PositiveIntegerField()),
                ('jins', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=5, null=True)),
                ('shahar', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
