# Generated by Django 4.2 on 2023-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_profil_tugilgan_yil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='jins',
            field=models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
